cargo-features = ["edition2021"]

[package]
name = "pacaptr-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.42"
itertools = "0.10.1"
litrs = "0.2.3"
once_cell = "1.8.0"
proc-macro2 = "1.0.27"
quote = "1.0.9"
regex = "1.5.4"
syn = "1.0.73"
tabled = "0.2.1"
